- hosts: all
  become: yes
  vars:
    log_file_path: "/var/log/test.log"

  tasks:
    - name: Get instance name from metadata
      shell: curl -s http://169.254.169.254/latest/meta-data/tags/instance/Name
      register: instance_name_result
      tags: always

    - name: Install common packages
      package:
        name:
          - wget
          - curl
          - unzip
          - python3
          - python3-pip
        state: present

    - name: Install Fluent Bit
      block:
        - name: Add Fluent Bit repository
          yum_repository:
            name: fluent-bit
            description: Fluent Bit repository
            baseurl: https://packages.fluentbit.io/amazonlinux/2
            gpgcheck: yes
            gpgkey: https://packages.fluentbit.io/fluentbit.key
            enabled: yes
        - name: Install Fluent Bit package
          package:
            name: fluent-bit
            state: present
        
        - name: Create Fluent Bit configuration
          template:
            src: fluent-bit.conf.j2
            dest: /etc/fluent-bit/fluent-bit.conf
      when: "'Fluent-Bit-Server' in instance_name_result.stdout"
      tags: fluent-bit

    - name: Add Elastic repository for Filebeat
      block:
        - name: Add Elastic repository
          yum_repository:
            name: elastic-8.x
            description: Elastic repository for 8.x packages
            baseurl: "https://artifacts.elastic.co/packages/8.x/yum"
            gpgcheck: yes
            gpgkey: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
            enabled: yes
        - name: Install Filebeat
          package:
            name: filebeat
            state: present
        
        - name: Create Filebeat configuration
          template:
            src: filebeat.yml.j2
            dest: /etc/filebeat/filebeat.yml
      when: "'Filebeat-Server' in instance_name_result.stdout"
      tags: filebeat

    - name: Install Promtail
      block:
        - name: Download Promtail
          shell: |
            ARCH=$(uname -m)
            VERSION=$(curl -s https://api.github.com/repos/grafana/loki/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
            wget https://github.com/grafana/loki/releases/download/${VERSION}/promtail-linux-${ARCH}.zip
            unzip promtail-linux-${ARCH}.zip
            chmod +x promtail-linux-${ARCH}
            mv promtail-linux-${ARCH} /usr/local/bin/promtail
          args:
            creates: /usr/local/bin/promtail
        
        - name: Create Promtail configuration
          template:
            src: promtail-config.yml.j2
            dest: /etc/promtail/config.yml
      when: "'Promtail-Server' in instance_name_result.stdout"
      tags: promtail

    - name: Create Log Generator Script and Service
      block:
        - name: Copy log generator script
          template:
            src: log_generator.sh.j2
            dest: /usr/local/bin/log_generator.sh
            mode: 0755

        - name: Create log generator systemd service
          template:
            src: log_generator.service.j2
            dest: /etc/systemd/system/log-generator.service

        - name: Enable and start log generator service
          systemd:
            name: log-generator
            enabled: yes
            state: started
      tags: log-generator
