---
- name: Install and Configure Log Shippers
  hosts: all
  become: yes
  vars: 
    log_file_path: "/var/log/test.log"  
  tasks:

    - name: Get instance name from metadata
      shell: curl -s http://169.254.169.254/latest/meta-data/tags/instance/Name
      register: instance_name_result
      tags: always

    - name: Install common packages
      apt:
        name:
          - wget
          - curl
          - unzip
        state: present
        update_cache: yes

    # Install Fluent Bit
    - name: Install Fluent Bit
      block:
        - name: Download libssl1.1 package
          shell: |
            wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb -O /tmp/libssl1.1.deb
          args:
            creates: /tmp/libssl1.1.deb

        - name: Install libssl1.1 package
          apt:
            deb: /tmp/libssl1.1.deb
            state: present

        - name: Import Fluent Bit GPG key
          apt_key:
            url: https://packages.fluentbit.io/fluentbit.key
            state: present

        - name: Add Fluent Bit repository
          apt_repository:
            repo: "deb https://packages.fluentbit.io/ubuntu/focal focal main"
            filename: fluentbit
            state: present

        - name: Install Fluent Bit package
          apt:
            name: fluent-bit
            state: present

        - name: Deploy Fluent Bit configuration
          template:
            src: templates/fluent-bit.conf.j2
            dest: /etc/fluent-bit/fluent-bit.conf

        - name: Restart and enable Fluent Bit service
          systemd:
            name: fluent-bit
            enabled: yes
            state: restarted
      when: "'FluentBit-Server' in instance_name_result.stdout"
      tags: fluent-bit

    # Install Filebeat
    - name: Install Filebeat
      block:
        - name: Import Elasticsearch GPG key
          apt_key:
            url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
            state: present

        - name: Add Elastic repository
          apt_repository:
            repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
            filename: elastic
            state: present

        - name: Install Filebeat
          apt:
            name: filebeat
            state: present

        - name: Deploy Filebeat configuration
          template:
            src: templates/filebeat.yml.j2
            dest: /etc/filebeat/filebeat.yml

        - name: Restart and enable Filebeat service
          systemd:
            name: filebeat
            enabled: yes
            state: restarted
      when: "'Filebeat-Server' in instance_name_result.stdout"
      tags: filebeat

    # Install Promtail
    - name: Install Promtail
      block:
        - name: Download and install Promtail
          shell: |
            ARCH=$(dpkg --print-architecture)
            VERSION=$(curl -s https://api.github.com/repos/grafana/loki/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
            wget https://github.com/grafana/loki/releases/download/${VERSION}/promtail-linux-${ARCH}.zip
            unzip promtail-linux-${ARCH}.zip
            chmod +x promtail-linux-${ARCH}
            mv promtail-linux-${ARCH} /usr/local/bin/promtail
          args:
            creates: /usr/local/bin/promtail

        - name: Deploy Promtail configuration
          template:
            src: templates/promtail-config.yml.j2
            dest: /etc/promtail/promtail-config.yml

        - name: Restart and enable Promtail service
          systemd:
            name: promtail
            enabled: yes
            state: restarted
      when: "'Promtail-Server' in instance_name_result.stdout"
      tags: promtail

    # Log Generator
    - name: Create Log Generator Script and Service
      block:
        - name: Deploy log generator script
          template:
            src: templates/log_generator.sh.j2
            dest: /usr/local/bin/log_generator.sh
            mode: 0755

        - name: Deploy log generator systemd service
          template:
            src: templates/log_generator.service.j2
            dest: /etc/systemd/system/log-generator.service

        - name: Enable and start log generator service
          systemd:
            name: log-generator
            enabled: yes
            state: restarted
      tags: log-generator

